### ISSUE TITLE
check state functions will fail to return a value when the conditional statement is not met

### ISSUE THREAD

**Issue by SammyOina** [nakujaproject/N2-flight-software#16]
https://github.com/nakujaproject/N2-flight-software/blob/dedff4ebea2c1c42b8ab2498e0856855e3436a6d/include/functions.h#L271-L308
control reaches end of non-void function [-Wreturn-type]

## Solution
add else statements to the conditional statements or "sentry" statement before the end of the functions

**Comment by SammyOina** [comment]
it also possible to squash them down to a single chechState function

**Comment by ianmuchyri** [comment]
Yeah, I will address the issue. This check state function may be the actual reason the parachute actually failed to eject.

**Comment by rodneyosodo** [comment]
Check current implementation [here](https://github.com/nakujaproject/N2-flight-software/blob/969ad9e360532d03477b0b8076134937260ff875/include/checkState.h#L72)

**Comment by SammyOina** [comment]
> Check current implementation [here](https://github.com/nakujaproject/N2-flight-software/blob/969ad9e360532d03477b0b8076134937260ff875/include/checkState.h#L72)

Looks good
