### ISSUE TITLE
Ejection() might get called multiple times 

### ISSUE THREAD

**Issue by georgebangeboss** [nakujaproject/N2-flight-software#24]
Find code [here](https://github.com/nakujaproject/N2-flight-software/blob/Launch/include/checkState.h)
Make a copy of this issue in the [internships2022 repo](https://github.com/nakujaproject/internship2022/issues)

**Comment by cmucheru** [comment]
- The function  `init checkApogee(){}`  runs once since the state will be different for the next execution.
